---
title: "Intro to R and R Markdown"
author: "James Gill"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("setup.R")
```

```{r}
data("penguins")
```

```{r}
class(penguins)
```

```{r}
str(penguins)
```

```{r}
class(penguins$species)
str(penguins$species)
```

```{r}
myList <- list("apple", 1993, FALSE, penguins)
str(myList)
```

```{r}
list(myList, list("more stuff here", list("and more")))
```

```{r}
names(myList) <- c("fruit", "year", "logic", "data")
names(myList)
```

```{r}
myList[[1]]
myList[["data"]]
```

```{r}
myVector <- c("apple", "banana", "pear")
myVector[2]
```

```{r}
penguins[1:5, 2]
penguins[1:5, "island"]
penguins[1, 1:5]
penguins [1:5, c("species","sex")]
penguins[penguins$sex=='female',]
```

# Exercises 6.3.1

##1

```{r}
myList["fruit"]
penguins$flipper_length_mm
penguins[penguins$island=='Dream',]
```

##2 Data was collected from three penguin species on Briscoe, Dream, and Torgersen islands.

```{r}
unique(penguins$species)
unique(penguins$island)
```

##3

```{r}
penguins[penguins$island=='Dream', c("species","island","flipper_length_mm")]
```

##4

```{r}
adelie_dream <- penguins[penguins$species=='Adelie'& penguins$island=='Dream',] 
mean(adelie_dream$flipper_length_mm, na.rm=TRUE)
```

```{r}
filter(penguins,species == "Adelie")
filter(penguins, species != "Adelie")
filter(penguins, island %in% c("Dream", "Torgensen") & !is.na(bill_length_mm))
```

```{r}
select(penguins, species, sex)
select(penguins, species:flipper_length_mm)
select(penguins, genus = species, island)
select(penguins, contains("mm"))
```

```{r}
mutate(penguins, bill_length_cm = bill_length_mm/10)
mutate(penguins, species_sex = if_else(sex=='male', paste0(species,"_m"), paste0(species, "_f")))
```

```{r}
penguins %>% 
  group_by(species) %>% 
  summarise(body_mass_avg = mean(body_mass_g, na.rm = TRUE))
```

```{r}
penguins %>% 
  group_by(species, year) %>% 
  summarise(n_observations = n())
```

#6.3.2 Exercises

##1

```{r}
penguins %>%
  select(year, everything())
```

##2

```{r}
mutate(penguins, size_group = if_else(body_mass_g>mean(body_mass_g, na.rm = TRUE), "large", "small")) 
```

##3

```{r}
penguins%>%
  group_by(year, species)%>%
  summarise(mean(body_mass_g, na.rm=TRUE))
```

##4

```{r}
penguins %>% 
  filter(year < c(2008, 2009))
```

```{r}
ggplot(penguins) + 
  geom_histogram(mapping = aes(x = flipper_length_mm))
```

```{r}
ggplot(penguins) +
  geom_histogram(aes(x = flipper_length_mm, fill = species), alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c("darkorange","darkorchid","cyan4"))
```

```{r}
ggplot(penguins) +
  geom_histogram(aes(x = flipper_length_mm, fill = species), alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c("darkorange","darkorchid","cyan4")) +
  facet_wrap(~species)
```

```{r}
ggplot(penguins) +
  geom_bar(mapping = aes(x = island, fill = species))
```

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(alpha = 0.8) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"), 
                    guide = FALSE) +
  theme_minimal() +
  facet_wrap(~species, ncol = 1) +
  coord_flip()
```

```{r}
ggplot(penguins) +
  geom_point(mapping = aes(x = body_mass_g, y = flipper_length_mm, color = species))
```

#7.1 Exercises
##1
```{r}
penguins%>%
  group_by(species)%>%
  summarise(average_flipper = mean(flipper_length_mm, na.rm=TRUE))%>%
  ggplot(mapping = aes(x=species,y=average_flipper,fill=species))

  
```
##2
```{r}
penguins%>%
  filter(island=="Dream")%>%
  ggplot(penguins)+
  geom_point(mapping=aes(x = bill_length_mm, y = bill_depth_mm, color=species))
```

